version: "3.9"

services:
  warehouse:
    image: postgres:15
    container_name: retail_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: retail_admin
      POSTGRES_PASSWORD: retail_pw
      POSTGRES_DB: retail_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_admin -d retail_warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
